function [ ref ] = getRef( sz,voxelDimesions )
ref = imref3d(sz,...
        voxelDimesions(1)/2*sz(2)*[-1 1],...
        voxelDimesions(2)/2*sz(1)*[-1 1],...
        voxelDimesions(3)/2*sz(3)*[-1 1]);

end

